"""
Task 1: Article Type Classification - Test & Evaluation Script
==============================================================

INSTRUCTIONS / HOW TO TEST:
---------------------------
Run all commands from the project root directory with your virtual environment activated:

1. Test a single image:
   python -m tasks.task1_article_type.test --image path/to/sample.jpg
   python -m tasks.task1_article_type.test --image A2_FashionDataset/FashionDataset/train/images_train/1163.jpg

2. Test on N random validation samples and export visual debug plots:
   python -m tasks.task1_article_type.test --random 10
   (Outputs saved to: outputs/test_debug/)

3. Generate predictions for the test set and export CSV:
   python -m tasks.task1_article_type.test --generate-predictions
   (Output saved to: outputs/task1_test_predictions.csv)

Note: Ensure models/cnn_articleType.keras and models/label_encoder_articleType.joblib 
exist before running (generated by tasks.task1_article_type.train).
"""

import os
import sys
import argparse
import logging
from pathlib import Path
import random
import pandas as pd
import numpy as np
import joblib
from PIL import Image
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import tensorflow as tf

# Suppress verbose TF warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
logging.getLogger('tensorflow').setLevel(logging.ERROR)
try:
    import absl.logging
    absl.logging.set_verbosity(absl.logging.ERROR)
except Exception:
    pass

# ---------------------------------------------------------------------------
# 1. Setup & Configuration
# ---------------------------------------------------------------------------
SEED = 42
MODEL_DIR = Path("models")
OUTPUT_DIR = Path("outputs")
CACHE_DIR = Path("cache")
ROOT = Path(".")

# Ensure directories exist
MODEL_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
CACHE_DIR.mkdir(parents=True, exist_ok=True)

# Dataset root directory (leave empty to use default A2_FashionDataset/FashionDataset)
folder_path = ""

target_value = "articleType"

# ---------------------------------------------------------------------------
# 2. Self-contained replacement for load_metadata and get_split
# ---------------------------------------------------------------------------
def load_metadata_self_contained(verbose=False):
    """
    Reconstructs metadata and labels split directly from local CSV.
    Guarantees consistent train/validation index mapping.
    """
    base_dir = folder_path if folder_path != "" else "A2_FashionDataset/FashionDataset"
    csv_path = os.path.join(base_dir, "train", "styles_train.csv")
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Missing styles_train.csv at: {csv_path}. Please check folder_path.")
        
    df = pd.read_csv(csv_path, on_bad_lines='skip')
    df = df.iloc[:, :10]  # Drop junk columns
    
    # Filter missing/invalid images
    img_dir = os.path.join(base_dir, "train", "images_train")
    df['img_path'] = df['id'].apply(lambda x: os.path.join(img_dir, f"{x}.jpg"))
    valid_mask = df['img_path'].apply(os.path.exists)
    df = df[valid_mask].reset_index(drop=True)
    
    # Filter out missing labels if any to perfectly match get_split
    df = df.dropna(subset=[target_value]).reset_index(drop=True)
    
    # Split using same random state
    from sklearn.model_selection import train_test_split
    train_df, val_df = train_test_split(df, test_size=0.2, random_state=SEED)
    
    return train_df.reset_index(drop=True), val_df.reset_index(drop=True)

def get_split_self_contained(target_value="articleType", normalised=True, verbose=False):
    """
    Loads dataset splits.
    Replaces get_split from src.data.
    """
    cache_prefix = CACHE_DIR / f"task1_{target_value}"
    X_train_path = f"{cache_prefix}_X_train.npy"
    X_val_path = f"{cache_prefix}_X_val.npy"
    y_train_path = f"{cache_prefix}_y_train.npy"
    y_val_path = f"{cache_prefix}_y_val.npy"
    encoder_path = MODEL_DIR / f"label_encoder_{target_value}.joblib"
    
    if os.path.exists(X_train_path) and os.path.exists(X_val_path) and os.path.exists(y_train_path) and os.path.exists(y_val_path) and os.path.exists(encoder_path):
        X_train = np.load(X_train_path)
        X_val = np.load(X_val_path)
        y_train = np.load(y_train_path)
        y_val = np.load(y_val_path)
        le = joblib.load(encoder_path)
    else:
        if verbose:
            print("Caching dataset splits...")
        base_dir = folder_path if folder_path != "" else "A2_FashionDataset/FashionDataset"
        csv_path = os.path.join(base_dir, "train", "styles_train.csv")
        if not os.path.exists(csv_path):
            raise FileNotFoundError(f"Missing styles_train.csv at: {csv_path}. Please check folder_path.")
            
        df = pd.read_csv(csv_path, on_bad_lines='skip')
        df = df.iloc[:, :10]
        img_dir = os.path.join(base_dir, "train", "images_train")
        df['img_path'] = df['id'].apply(lambda x: os.path.join(img_dir, f"{x}.jpg"))
        valid_mask = df['img_path'].apply(os.path.exists)
        df = df[valid_mask].reset_index(drop=True)
        df = df.dropna(subset=[target_value]).reset_index(drop=True)
        
        from sklearn.preprocessing import LabelEncoder
        le = LabelEncoder()
        df['label'] = le.fit_transform(df[target_value])
        joblib.dump(le, encoder_path)
        
        from sklearn.model_selection import train_test_split
        train_df, val_df = train_test_split(df, test_size=0.2, random_state=SEED)
        
        def load_images_from_df(dataframe):
            images = []
            for path in dataframe['img_path']:
                try:
                    with Image.open(path) as img:
                        img = img.convert('RGB')
                        img = img.resize((60, 80))
                        images.append(np.array(img, dtype=np.uint8))
                except Exception:
                    images.append(np.zeros((80, 60, 3), dtype=np.uint8))
            return np.array(images, dtype=np.uint8)
            
        X_train_raw = load_images_from_df(train_df)
        X_val_raw = load_images_from_df(val_df)
        y_train = train_df['label'].values
        y_val = val_df['label'].values
        
        np.save(X_train_path, X_train_raw)
        np.save(X_val_path, X_val_raw)
        np.save(y_train_path, y_train)
        np.save(y_val_path, y_val)
        
        X_train = X_train_raw
        X_val = X_val_raw
        
    if normalised:
        X_train = X_train.astype(np.float32) / 255.0
        X_val = X_val.astype(np.float32) / 255.0
        
    return X_train, X_val, y_train, y_val, le

# ---------------------------------------------------------------------------
# 3. Core Test Functions
# ---------------------------------------------------------------------------
def load_model_and_encoder():
    """Load the trained Keras model and LabelEncoder."""
    try:
        model = tf.keras.models.load_model(MODEL_DIR / 'cnn_articleType.keras')
        le = joblib.load(MODEL_DIR / 'label_encoder_articleType.joblib')
        return model, le
    except Exception as e:
        print(f"Error: Unable to locate or load model / encoder at: {MODEL_DIR}")
        print("Please train the model first by running:")
        print("   python -m tasks.task1_article_type.train")
        print(f"Details: {e}")
        sys.exit(1)

def preprocess_image(image_path):
    """Preprocess a single image file to dimensions (80, 60)."""
    try:
        img = tf.keras.preprocessing.image.load_img(image_path, target_size=(80, 60))
        x = tf.keras.preprocessing.image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        x = x.astype(np.float32) / 255.0
        return x
    except Exception as e:
        print(f"Error preprocessing image {image_path}: {e}")
        sys.exit(1)

def mode_single_image(image_path):
    """Predict category for a single image file."""
    if not os.path.exists(image_path):
        print(f"Error: Image not found at '{image_path}'.")
        return
        
    model, le = load_model_and_encoder()
    x = preprocess_image(image_path)
    
    preds = model.predict(x, verbose=0)[0]
    class_idx = np.argmax(preds)
    confidence = preds[class_idx] * 100
    class_name = le.classes_[class_idx]
    
    print(f"\nImage:       {image_path}")
    print(f"Predicted:   {class_name}")
    print(f"Confidence:  {confidence:.2f}%\n")

def mode_random_validation(n_samples):
    """Evaluate on random validation samples and save labeled debug images."""
    model, le = load_model_and_encoder()
    
    print("\nLoading validation dataset and metadata...")
    try:
        _, val_df = load_metadata_self_contained(verbose=False)
    except Exception as e:
        print(f"Error: Failed to construct metadata for image ID mapping: {e}")
        sys.exit(1)
        
    _, X_val, _, y_val, _ = get_split_self_contained('articleType', verbose=False)
    
    n_samples = min(n_samples, len(X_val))
    indices = random.sample(range(len(X_val)), n_samples)
    
    X_sample = X_val[indices]
    y_sample_true = y_val[indices]
    
    preds = model.predict(X_sample, verbose=0)
    y_sample_pred = np.argmax(preds, axis=1)
    
    debug_dir = OUTPUT_DIR / "test_debug"
    debug_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"\nEVALUATING {n_samples} RANDOM VALIDATION SAMPLES:\n")
    header = f"{'Index':<8} | {'Image ID':<10} | {'True Label':<24} | {'Predicted Label':<24} | {'Confidence':<10} | {'Status'}"
    print(header)
    print("-" * len(header))
    
    correct_count = 0
    for i, idx in enumerate(indices):
        image_id = str(val_df.iloc[idx]['id'])
        true_label = le.classes_[y_sample_true[i]]
        pred_label = le.classes_[y_sample_pred[i]]
        conf = np.max(preds[i]) * 100
        
        is_correct = (y_sample_true[i] == y_sample_pred[i])
        status = "CORRECT" if is_correct else "WRONG"
        if is_correct:
            correct_count += 1
            
        print(f"{idx:<8} | {image_id:<10} | {true_label:<24} | {pred_label:<24} | {conf:>7.2f}%   | {status}")
        
        # Ensure values are safely clipped for plotting
        img_arr = X_sample[i].copy()
        img_arr = np.clip(img_arr, 0.0, 1.0)
        
        # Save image with prediction text
        fig, ax = plt.subplots(figsize=(3, 4))
        ax.imshow(img_arr)
        ax.axis('off')
        title_color = 'green' if is_correct else 'red'
        ax.set_title(
            f"Index: {idx} | ID: {image_id}\nTrue: {true_label}\nPred: {pred_label} ({conf:.1f}%)",
            fontsize=9,
            color=title_color,
            pad=6
        )
        safe_true = true_label.replace(" ", "_").replace("/", "-")
        safe_pred = pred_label.replace(" ", "_").replace("/", "-")
        save_filename = f"idx_{idx}_id_{image_id}_true_{safe_true}_pred_{safe_pred}.png"
        fig.savefig(debug_dir / save_filename, bbox_inches='tight', dpi=120)
        plt.close(fig)
        
    print("-" * len(header))
    acc = (correct_count / n_samples) * 100
    print(f"Accuracy on random samples: {correct_count}/{n_samples} ({acc:.2f}%)")
    print(f"\nVisual debug images saved to: {debug_dir}/")

def mode_generate_predictions():
    """Predict for the hidden test folder and export predictions CSV."""
    model, le = load_model_and_encoder()
    
    base_dir = folder_path if folder_path != "" else "A2_FashionDataset/FashionDataset"
    test_dir = Path(base_dir) / "test" / "images_test"
    image_paths = list(test_dir.glob("*.jpg"))
    if not image_paths:
        print(f"Error: No .jpg images found in test directory: '{test_dir}'")
        return
        
    print(f"\nFound {len(image_paths)} images in test set. Generating predictions...")
    
    ids = []
    predictions = []
    
    batch_size = 128
    for i in range(0, len(image_paths), batch_size):
        batch_paths = image_paths[i:i+batch_size]
        batch_ids = [p.stem for p in batch_paths]
        
        batch_images = []
        for p in batch_paths:
            img = tf.keras.preprocessing.image.load_img(p, target_size=(80, 60))
            x = tf.keras.preprocessing.image.img_to_array(img)
            batch_images.append(x)
            
        X_batch = np.array(batch_images, dtype=np.float32) / 255.0
            
        preds = model.predict(X_batch, verbose=0)
        pred_classes = np.argmax(preds, axis=1)
        pred_labels = le.inverse_transform(pred_classes)
        
        ids.extend(batch_ids)
        predictions.extend(pred_labels)
        
        processed = min(i + batch_size, len(image_paths))
        if processed % (batch_size * 5) == 0 or processed == len(image_paths):
            print(f"  Processed {processed}/{len(image_paths)} images...")
            
    # Export CSV
    df = pd.DataFrame({"id": ids, "predicted_articleType": predictions})
    out_path = OUTPUT_DIR / "task1_test_predictions.csv"
    df.to_csv(out_path, index=False)
    
    print(f"\nSuccessfully generated predictions file: {out_path}")
    print(f"Total rows exported: {len(df)}\n")

# ---------------------------------------------------------------------------
# 4. CLI Entry Point
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="CLI for evaluating and testing articleType (Self-Contained)")
    parser.add_argument("--image", type=str, help="Path to a single image for prediction")
    parser.add_argument("--random", type=int, help="Number of random validation samples to evaluate")
    parser.add_argument("--generate-predictions", action="store_true", help="Generate predictions on hidden test set")
    args = parser.parse_args()
    
    if args.image:
        mode_single_image(args.image)
    elif args.random is not None:
        mode_random_validation(args.random)
    elif args.generate_predictions:
        mode_generate_predictions()
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
